### ISSUE TITLE
should not require gulp as a dependency

### ISSUE THREAD

**Issue by stephenlacy** [morishitter/gulp-acss#1]
gulp plugins should not require gulp as any dependency.
https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md

**Comment by msaktype** [comment]
Sorry, I fixed and released v0.1.1. https://github.com/morishitter/gulp-acss/commit/ade8e0e52ce511f0f18000f15a7c531f5a4efb70
Thanks :)
